name: CD

on:
  push:
    branches: 
      - master

jobs:
  deploy:
    name: Deploy to Github Pages 
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: install dependencies, build and run tests
      run: |
        yarn install
        yarn deploy