name: CI-tests

on:
  pull_request:
    branches: 
      - master
      - develop

jobs:
  test:
    name: Unit tests 
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: install dependencies, build and run tests
      run: |
        yarn install
        yarn run build --if-present
        yarn test:coverage
    

